# -*- coding: utf-8 -*-
"""Deutchemeister

Automatically generated by Colab.

"""

import http.client
import urllib.parse
import json
import pandas as pd
import os

"""MATCH DETAILS and Fixture idss"""

conn = http.client.HTTPSConnection("v3.football.api-sports.io")

headers = {
    'x-rapidapi-host': "v3.football.api-sports.io",
    'x-rapidapi-key': "xx"
    }

# Parameters
league_id = 78 # Example: Premier League
season = 2025
status = "FT"  # Finished matches
round_number = "Regular Season - 26"  # Example round

params = {
    "league": league_id,
    "season": season,
    "status": status,
    "round": round_number
}

# Construct the request URL with parameters
request_url = f"/fixtures?{urllib.parse.urlencode(params)}"

conn.request("GET", request_url, headers=headers)

res = conn.getresponse()
data = res.read()

# print(data.decode("utf-8"))

# Load the JSON data
data_dict = json.loads(data)

# Extract relevant information
matches = data_dict['response']

# Create a DataFrame
mn = pd.DataFrame([{
    'fixture_id': match['fixture']['id'],
    'referee': match['fixture']['referee'],
    'date': match['fixture']['date'],
    'venue': match['fixture']['venue']['name'],
    'city': match['fixture']['venue']['city'],
    'status': match['fixture']['status']['long'],
    'league': match['league']['name'],
    'season': match['league']['season'],
    'round': match['league']['round'],
    'home_team': match['teams']['home']['name'],
    'away_team': match['teams']['away']['name'],
    'home_goals': match['goals']['home'],
    'away_goals': match['goals']['away'],
    'winner': 'home' if match['teams']['home']['winner'] else 'away' if match['teams']['away']['winner'] else 'draw'
} for match in matches])

"""Code to get fixture results"""

import time
import json
import http.client
import pandas as pd

fixture_ids = mn['fixture_id'].tolist()

HEADERS = {
    'x-rapidapi-host': "v3.football.api-sports.io",
    'x-rapidapi-key': "d4f2008477eb335e927b37a3f91fe909"
}

def fetch_statistics(fixture_id, retries=2, wait=15):
    """
    Fetch fixture statistics with limited retries (free-tier safe).
    Returns response list if successful, else None.
    """
    for attempt in range(1, retries + 1):
        try:
            conn = http.client.HTTPSConnection(
                "v3.football.api-sports.io",
                timeout=25
            )
            request_url = f"/fixtures/statistics?fixture={fixture_id}"
            conn.request("GET", request_url, headers=HEADERS)

            res = conn.getresponse()
            data = json.loads(res.read().decode("utf-8"))

            if data.get("response") and len(data["response"]) == 2:
                return data["response"]

            print(
                f"Fixture {fixture_id}: attempt {attempt}/{retries} "
                f"returned {len(data.get('response', []))} teams"
            )

        except Exception as e:
            print(f"Fixture {fixture_id}: error on attempt {attempt} → {e}")

        time.sleep(wait)

    return None


all_stats = []
failed_fixtures = []

for fixture_id in fixture_ids:
    print(f"Fetching data for fixture ID: {fixture_id}")

    response = fetch_statistics(fixture_id)

    if response is None:
        print(f"Fixture {fixture_id}: FAILED after retries")
        failed_fixtures.append(fixture_id)
        continue

    home_team = mn.loc[mn['fixture_id'] == fixture_id, 'home_team'].iloc[0]
    away_team = mn.loc[mn['fixture_id'] == fixture_id, 'away_team'].iloc[0]

    for stat in response:
        team_name = stat['team']['name']

        home_away = (
            'H' if team_name == home_team
            else 'A' if team_name == away_team
            else None
        )

        stat_flat = {
            "fixture_id": fixture_id,
            "team_id": stat['team']['id'],
            "team_name": team_name,
            "H/A": home_away
        }

        for item in stat['statistics']:
            stat_flat[item['type']] = item['value']

        all_stats.append(stat_flat)

    time.sleep(1)  # rate-limit friendly pause


ozil = pd.DataFrame(all_stats)

# Safety check: each fixture must have exactly 2 rows
counts = ozil.groupby("fixture_id").size()
bad_fixtures = counts[counts != 2]

if not bad_fixtures.empty:
    print("WARNING: Incomplete fixtures detected:")
    print(bad_fixtures)

print(f"Completed fixtures: {ozil['fixture_id'].nunique()} / {len(fixture_ids)}")
print(f"Failed fixtures: {len(failed_fixtures)}")

mn[['round', 'season_number']] = mn['round'].str.split(' - ', expand=True)
mn['round'] = mn['season_number']
mn['date'] = pd.to_datetime(mn['date'])

columns_to_fill = [
    'Shots on Goal', 'Shots off Goal',
    'Total Shots', 'Blocked Shots', 'Shots insidebox', 'Shots outsidebox',
    'Fouls', 'Corner Kicks', 'Offsides', 'Yellow Cards', 'Red Cards',
    'Goalkeeper Saves', 'Total passes', 'Passes accurate', 'expected_goals',
]

# Apply fillna(0) to each column
for column in columns_to_fill:
    ozil[column] = ozil[column].fillna(0)

"""Engineering data for team v opp"""

combined_df = pd.merge(ozil, mn, how='left', on='fixture_id')


# Add columns for goals and match date
combined_df['date'] = combined_df['date']
combined_df['team_goals'] = combined_df.apply(
    lambda x: x['home_goals'] if x['team_name'] == x['home_team'] else x['away_goals'], axis=1
)
combined_df['opponent_goals'] = combined_df.apply(
    lambda x: x['away_goals'] if x['team_name'] == x['home_team'] else x['home_goals'], axis=1
)


# Select relevant columns
x_df = combined_df[['fixture_id', 'team_id','H/A', 'team_name', 'date', 'team_goals', 'opponent_goals',
                        'Shots on Goal', 'Shots off Goal', 'Total Shots', 'Blocked Shots','Shots insidebox', 'Shots outsidebox', 'Fouls', 'Corner Kicks', 'Offsides', 'Ball Possession', 'Yellow Cards', 'Red Cards', 'Goalkeeper Saves', 'Total passes', 'Passes accurate', 'Passes %', 'expected_goals','round', 'season', 'league']]



# Select relevant columns
opp_df = combined_df[['fixture_id', 'team_id', 'team_name',
                        'Shots on Goal', 'Shots off Goal', 'Total Shots', 'Blocked Shots','Shots insidebox', 'Shots outsidebox', 'Fouls', 'Corner Kicks', 'Offsides', 'Ball Possession', 'Yellow Cards', 'Red Cards', 'Goalkeeper Saves', 'Total passes', 'Passes accurate', 'Passes %', 'expected_goals']]


final_df = pd.merge(x_df, opp_df, how='left', on='fixture_id', suffixes=('', '_opp'))
final_df = final_df[final_df['team_id'] != final_df['team_id_opp']]
final_df.rename(columns={'team_name_opp': 'opponent', 'league': 'competition'}, inplace=True)
final_df.drop(columns=['team_id','team_id_opp'], inplace=True)
final_df['date'] = pd.to_datetime(final_df['date'],format= "%Y-%m-%d")
# final_df[['date', 'time']] = final_df['date'].str.split( ' ', expand=True)

print("18 teams of", final_df.shape[0])

file_path = '/content/drive/MyDrive/Football_Haven/Stats_Deutche.csv'

# Check if the file exists, and if so, delete it
if os.path.exists(file_path):
    os.remove(file_path)
    print(f"Deleted existing file: {file_path}")
else:
    print(f"No file to delete at: {file_path}")

# Save the new DataFrame to the file
final_df.to_csv(file_path, index=False)
print(f"New file saved: {file_path}")